name: cari_hesapp_lite
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

  
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    

  flutter_phoenix: ^1.0.0
  
  font_awesome_flutter: ^9.2.0
  
  freezed_annotation: any

  flutter_svg: ^0.23.0+1

  #sqflite: ^1.3.1+1
  shared_preferences:
  http: ^0.13.4
  path: ^1.8.0
  path_provider:

   
  firebase_auth: ^ 3.2.0 
  
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.2.4
  firebase_core:

  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1

  url_launcher: ^6.0.18
  
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.1
  #intl:
  carousel_slider: ^4.0.0

  #for currency usage
  currency_textfield: ^2.0.0
  #for textfield format
  easy_mask: ^2.0.1
  
  #for validation
  #fzregex:
  lottie: ^1.2.1
  
  #place_picker: ^0.9.18
  location: ^4.3.0
  flutter_slidable: ^1.1.0 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2
  # hive: 
  # hive_flutter:

  fl_chart: ^0.35.0
  charts_flutter: ^0.12.0
  #syncfusion_flutter_charts: ^19.1.57+1

  #for CPIndicator
  flutter_spinkit:

  #for slider page
  #transformer_page_view:
  #flutter_swiper: ^1.1.6
  flutter_swiper_plus: ^2.0.4

  #https://pub.dev/packages/supercharged/install
  #TODO faydali bir paket daha sonra incele
  #supercharged: ^2.0.0

  kartal: ^2.2.1
  
  simple_animations: ^4.0.1

  curved_navigation_bar: ^1.0.1

  #for credit card entry
  #https://pub.dev/packages/awesome_card
  #awesome_card: ^1.1.5


  #flutter_barcode_scanner:

  #revenuecat ödeme yöntemi
  purchases_flutter: ^3.0.0 

  #money_converter: ^0.0.4

  geolocator: ^8.0.1
  google_maps_flutter: 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/user_default_avatar.png
  
  - assets/icons/
  - assets/lottie/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Monoisome
      fonts:
       - asset: fonts/Monoisome-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: DejaVu
      fonts:
       - asset: fonts/DejaVuSansMono.ttf
    - family: Pragmata
      fonts:
       - asset: fonts/Pragmata_Medium.ttf

    - family: Signika
      fonts: 
       - asset: fonts/Signika-Bold.ttf
       - asset: fonts/Signika-Light.ttf
       - asset: fonts/Signika-Medium.ttf
       - asset: fonts/Signika-Regular.ttf
       - asset: fonts/Signika-SemiBold.ttf

       - style: normal

    - family: Quicksand
      fonts:
       - asset: fonts/Quicksand/Quicksand-Medium.ttf
       - style: normal
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
